# Generated by Django 3.2 on 2022-08-11 18:26

from django.db import migrations, models
import django.db.models.deletion
import strapi_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.JSONField(default=strapi_app.models.get_default_something, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=20)),
                ('picture_url', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('picture_url', models.CharField(max_length=600)),
                ('people', models.ManyToManyField(to='strapi_app.People')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strapi_app.planet')),
            ],
        ),
    ]
