# Generated by Django 3.2 on 2022-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strapi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='picture_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='planet',
            name='picture_url',
            field=models.CharField(max_length=200),
        ),
    ]
