# Generated by Django 3.2 on 2022-08-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strapi_app', '0002_auto_20220806_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='picture_url',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='planet',
            name='picture_url',
            field=models.CharField(max_length=600),
        ),
    ]
