# Generated by Django 3.2 on 2022-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strapi_app', '0004_auto_20220808_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='type_people',
        ),
        migrations.RemoveField(
            model_name='people',
            name='types',
        ),
        migrations.AddField(
            model_name='character',
            name='people',
            field=models.ManyToManyField(to='strapi_app.People'),
        ),
        migrations.AddField(
            model_name='people',
            name='friends',
            field=models.JSONField(default='solomon', max_length=100),
        ),
    ]
