# Generated by Django 3.2 on 2022-08-08 22:26

from django.db import migrations, models
import strapi_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('strapi_app', '0005_auto_20220808_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='friends',
            field=models.JSONField(default=strapi_app.models.get_default_something, max_length=100),
        ),
    ]
